# Generated by Django 5.0.7 on 2024-08-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('nome_struttura', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('indirizzo', models.CharField(max_length=200)),
                ('struttura_padre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('titolo', models.CharField(max_length=200)),
                ('struttura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.struttura')),
            ],
        ),
    ]
