# Generated by Django 5.0.7 on 2024-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struttura',
            name='struttura_padre',
        ),
        migrations.AddField(
            model_name='struttura',
            name='struttura_padre_id',
            field=models.IntegerField(null=True),
        ),
    ]
