# Generated by Django 5.0.7 on 2024-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_remove_struttura_struttura_padre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='struttura',
            name='struttura_padre_id',
        ),
        migrations.AddField(
            model_name='struttura',
            name='struttura_padre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
