# Generated by Django 5.0.7 on 2024-08-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_alter_utenti_struttura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utenti',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.struttura'),
        ),
    ]
